Repository Shubham-Zone/Citizen_Squad, pull requests merged in 2024-10, with the labels that each got.

#20 Create Code_of_conduct.md
  Code_of_conduct.md
Labels: gssoc-ext, level1

#22 added troubleshooting section to readme
  README.md
Labels: gssoc-ext

#26 Contributing.md file added
  Contributing.md
Labels: gssoc-ext

#40 Security Guidelines Updated
  Security.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#46 Added MIT License as LICENSE.md in the repository
  LICENSE.md
Labels: gssoc-ext, level1

#51 Added Test number and OTP
  README.md
Labels: gssoc-ext, level1

#50 Added SRS Word and PDF files
  srs_citizen_squad.doc
  srs_citizen_squad.pdf
Labels: gssoc-ext, hacktoberfest-accepted

#55 CREATE BUG REPORT TEMPLATE
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1
